add multi-arch (#1)
* Update docker-publish.yml

* Update docker-publish.yml

* Update build-rootfs.py

* Update build-rootfs.py

* Update build-rootfs.py

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update Dockerfile

* Update Dockerfile

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update build-rootfs.py

* Update build-rootfs.py

* Update build-rootfs.py

* Update docker-publish.yml

* Create dependabot.yml

* Update build-rootfs.py

* Update build-rootfs.py

* Update build-rootfs.py

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -2,21 +2,361 @@ name: Build and push image
 
 on:
   push:
+  workflow_dispatch:
+    inputs:
+      clear-docker-cache:
+        description: 'clear docker cache with rm -fr /tmp/.buildx-cache /tmp/.buildx-cache-old /tmp/.buildx-cache-new'     
+        required: false 
+        type: boolean
+
+# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets
+# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
+permissions:
+  packages: read
+  contents: read
+
+concurrency: 
+  group: ${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
 
 jobs:
+  pre_job:
+    runs-on: ubuntu-20.04
+    name: pre_job
+    steps:
+      - name: pre_job Set up Docker Buildx
+        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' || runner.os != 'Windows' }}
+        id: buildx
+        uses: docker/setup-buildx-action@v2.0.0
+      - name: pre_job CI Build
+        id: docker_build
+        uses: docker/build-push-action@v3.0.0
+        with:
+          platforms: linux/amd64
+          push: false
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          build-args: "BASE_IMAGE=ubuntu:20.04"
+
   build-push:
-    runs-on: ubuntu-latest
+    ## name: build-${{ matrix.matrixjobname }}
+    needs: pre_job
+    runs-on: ${{ matrix.host-os }}
+    ###  continue-on-error: ${{ matrix.experimental }}
+    # see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
+    # https://github.com/apache/commons-io/blob/5911ca64d08c110bc7a612dbef2f278d5dd2a9ab/.github/workflows/maven.yml#L23
+    strategy:
+#      fail-fast: true
+      fail-fast: false
+      matrix:
+        platform-args:
+          - "linux/amd64"
+#          - "linux/amd64/v2"
+#          - "linux/amd64/v3"
+#          - "linux/amd64/v4"
+          - "linux/arm64"
+#          - "linux/riscv64"
+          - "linux/ppc64le"
+          - "linux/s390x"
+          - "linux/386"
+          - "linux/mips64le"
+#          - "linux/mips64"
+          - "linux/arm/v7"
+          - "linux/arm/v6"
+          - "linux/arm/v5"
+#          - "linux/arm/v4"
+          #linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
+          #- linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
+          #- "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64"
+        matrixjobname: 
+          - "build1"
+        #host-os:
+          #- ubuntu-18.04
+          #- ubuntu-20.04
+        #host-os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest, windows-2016, windows-2019, windows-2022, macos-10.15, macos-11, macos-12]
+        #host-os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest, windows-2016, windows-2019, windows-2022, macos-10.15, macos-11, macos-12]
+        host-os: [ubuntu-20.04]
+        release:
+          - false
+        tag-args:
+          - "null"
+        tag-latest: [FALSE]
+        tag-sha: [FALSE]
+        tag-args-enable: [FALSE]
+        tag-args-disable: [TRUE]
+        setup-qemu: [TRUE]
+        setup-buildx: [TRUE]
+        # tag-args-enable: 
+        #  - false
+        experimental: [true]
+        build-args:
+          - "BASE_IMAGE="
+          #- "BASE_IMAGE=ubuntu:20.04"
+          #- "BASE_IMAGE=debian:11.2-slim"
+        #"BASE_IMAGE=alpine:edge"
+        #"BASE_IMAGE=localhost:5000/my-project/base"
+        include:
+#          #- platform-args: "linux/amd64,linux/arm64,linux/arm/v7"
+#          - platform-args: "linux/amd64"
+#            #host-os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-2016, windows-2019, windows-2022, macos-10.15, macos-11, macos-12]
+#            host-os: ubuntu-22.04
+#            #host-os: ubuntu-latest
+#            tag-args: hostos-test-
+#            tag-latest: false
+#            tag-sha: false
+#            tag-args-enable: true
+#            tag-args-disable: false
+#            #build-args: 'BASE_IMAGE=ubuntu:20.04'
+#            build-args: 'BASE_IMAGE=ubuntu:22.04'
+#            #release: false
+#            #release: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+#            release: true
+#            experimental: true
+          #- platform-args: linux/riscv64
+          #- platform-args: "linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64,linux/386,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x"
+#          - platform-args: "linux/amd64"
+#            #host-os: ubuntu-latest
+#            host-os: ubuntu-20.04
+#            tag-args: debian-unstable-
+#            tag-latest: false
+#            tag-sha: false
+#            tag-args-enable: true
+#            tag-args-disable: false
+#            #build-args: 'BASE_IMAGE=debian:unstable-20220527-slim'
+#            build-args: 'BASE_IMAGE=debian:unstable-slim'
+#            #release: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+#            release: false
+#            experimental: true
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64"
+          # no linux/mips64 support
+          #- platform-args: "linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64,linux/386,linux/mips64le,linux/ppc64le,linux/s390x"
+#          - platform-args: "linux/amd64"
+#            host-os: ubuntu-latest
+#            tag-args: debian-
+#            tag-latest: false
+#            tag-sha: false
+#            tag-args-enable: true
+#            tag-args-disable: false
+#            build-args: 'BASE_IMAGE=debian:11.2-slim'
+#            #release: true
+#            #release: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+#            release: true
+#            experimental: true
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/mips64le,linux/riscv64,linux/ppc64le,linux/s390x"
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"
+          - platform-args: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/mips64le,linux/ppc64le,linux/s390x"
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/mips64le,linux/riscv64,linux/ppc64le,linux/s390x"
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v4,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/mips64le,linux/riscv64,linux/ppc64le,linux/s390x"
+          #- platform-args: "linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x"
+          #- platform-args: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64"
+          #- platform-args: "linux/amd64"
+            host-os: ubuntu-20.04
+            tag-args: ''
+            tag-latest: true
+            tag-sha: false
+            tag-args-enable: false
+            tag-args-disable: false
+            #build-args: 'BASE_IMAGE=ubuntu:20.04'
+            build-args: 'BASE_IMAGE='
+            setup-qemu: true
+            setup-buildx: true
+            #release: false
+            #release: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+            release: true
+            experimental: true
+    permissions:
+      packages: write
+      contents: read
 
     steps:
       - uses: actions/checkout@v2
+
       - name: Set up QEMU
+        if: ${{ matrix.setup-qemu }}
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
+        if: ${{ matrix.setup-buildx }}
         id: buildx
         uses: docker/setup-buildx-action@v2
       - name: Available platforms
         run: echo ${{ steps.buildx.outputs.platforms }}
-      - name: Log into DockerHub
-        run: echo "${{ secrets.DH_PAT }}" | docker login -u fwilhe2 --password-stdin
+
+#######################################################
+      - name: Generate hash of matrix.platform-args AND matrix.build-args
+        shell: bash
+        env:
+          MATRIX_TAG_ARGS_ENABLE: ${{matrix.tag-args-enable}}
+          MATRIX_TAG_ARGS_DISABLE: ${{matrix.tag-args-disable}}
+        run: |
+          set -vx
+          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#echoing-command-outputs
+          #echo '::echo::on'
+          echo "[debug] github.sha is '${{ github.sha }}'"
+          short_sha=$(echo "${{ github.sha }}" | cut -c1-8 )
+          echo "[debug] Generated short_sha is '${short_sha}'"
+          echo "::set-output name=short_sha::$short_sha"
+          #
+          echo "[debug] matrix.platform-args is '${{ matrix.platform-args }}'"
+          ### hash=$(echo "${{ matrix.platform-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | md5sum | cut -c1-15 )
+          hash=$(echo "${{ matrix.platform-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | shasum -a1 | cut -c1-8 )
+          echo "[debug] Generated hash is '${hash}'"
+          echo "::set-output name=hash::$hash"
+          #
+          echo "[debug] matrix.platform-args is '${{ matrix.platform-args }}'"
+          ### hash=$(echo "${{ matrix.platform-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | md5sum | cut -c1-15 )
+          pavar=$(echo "${{ matrix.platform-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | sed -e 's/^.*linux\//.L/g' -e 's/^.*windows\//.W/g' -e 's/^.*darwin\//.D/g' | tr -d '\n' | sed -e 's/[^0-9,a-z,A-Z,.]*//g' )
+          echo "[debug] Generated pavar is '${pavar}'"
+          echo "::set-output name=pavar::$pavar"
+          #
+          echo "[debug] matrix.build-args is '${{ matrix.build-args }}'"
+          ### bahash=$(echo "${{ matrix.build-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | md5sum | cut -c1-15 )
+          bahash=$(echo "${{ matrix.build-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | shasum -a1 | cut -c1-8 )
+          echo "[debug] Generated bahash is '${bahash}'"
+          echo "::set-output name=bahash::$bahash"
+          #
+          echo "[debug] matrix.build-args is '${{ matrix.build-args }}'"
+          bavar=$(echo "${{ matrix.build-args }}" | sed -e 's/[;, ]/\n/g' | sort -u | sed -e 's/^.*=/./g' | tr -d '\n' | sed -e 's/[^0-9,a-z,A-Z,.]*//g' )
+          echo "[debug] Generated bavar is '${bavar}'"
+          echo "::set-output name=bavar::$bavar"
+          #
+          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
+          echo "::set-output name=fulldate::$(/bin/date -u "+%Y%m%dT%H%M%S")"
+          #${{ steps.generate_matrix_platform-args.outputs.hash }}
+          #echo '::echo::off'
+        id: generate_matrix_platform-args
+#################
+      - name: Cache Docker layers
+        id: buildx-cache
+        uses: actions/cache@v3.0.4
+        with:
+          path: /tmp/.buildx-cache
+          # key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ github.run_id }}
+          # ${{ hashFiles('**/go.sum') }}-
+          # key: ${{ runner.os }}-buildx-HASH${{ steps.generate_matrix_platform-args.outputs.hash }}-CV${{ inputs.cache-version }}-SHA${{ github.sha }}-RUN${{ github.run_id }}-DATE${{ steps.generate_matrix_platform-args.outputs.fulldate }}
+          # key: ${{ runner.os }}-buildx-PAHASH${{ steps.generate_matrix_platform-args.outputs.hash }}-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-RUN${{ github.run_id }}-
+          key: ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-PA${{ steps.generate_matrix_platform-args.outputs.pavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-RUN${{ github.run_id }}-
+          # key: ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-PA${{ steps.generate_matrix_platform-args.outputs.pavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-
+          restore-keys: |
+            # ${{ runner.os }}-buildx-HASH${{ steps.generate_matrix_platform-args.outputs.hash }}-CV${{ inputs.cache-version }}-SHA${{ github.sha }}-RUN${{ github.run_id }}-DATE${{ steps.generate_matrix_platform-args.outputs.fulldate }}
+            # ${{ runner.os }}-buildx-PAHASH${{ steps.generate_matrix_platform-args.outputs.hash }}-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-RUN${{ github.run_id }}-
+            ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-PA${{ steps.generate_matrix_platform-args.outputs.pavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-RUN${{ github.run_id }}-
+            ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-PA${{ steps.generate_matrix_platform-args.outputs.pavar }}-SHA${{ steps.generate_matrix_platform-args.outputs.short_sha }}-
+            ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-PA${{ steps.generate_matrix_platform-args.outputs.pavar }}-
+            ${{ runner.os }}-buildx-BA${{ steps.generate_matrix_platform-args.outputs.bavar }}-
+            # ${{ runner.os }}-buildx-${{ github.sha }}-${{ github.run_id }}
+            # ${{ runner.os }}-buildx-${{ github.sha }}-
+            # ${{ runner.os }}-buildx-
+      # START workaround for --cache-from fails if cache does not already exist
+      - name: remove Docker cache
+        if: ${{ github.event.inputs.clear-docker-cache }}
+        run: rm -fr /tmp/.buildx-cache /tmp/.buildx-cache-old /tmp/.buildx-cache-new
+      - name: Docker cache Fix 1/2
+      # see
+      # https://github.com/actions/cache/issues/485
+      # https://github.com/shivammathur/cache-extensions/issues/22
+      # see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10365/files#diff-bc668a2c9f2299cef15b222055b4b4d5311646caec2e7610e540cee18ae9b948
+        ##if: steps.buildx-cache.outputs.cache-hit != 'true'
+        ##run: echo "START Docker cache Fix" || echo "FROM scratch" | docker buildx build - --cache-to type=local,dest=/tmp/.buildx-cache,mode=max
+        #run: |
+        #  [[ -f /tmp/.buildx-cache/index.json ]] || $( echo 'START Docker cache Fix' ; echo "FROM scratch" | docker buildx build - --cache-to type=local,dest=/tmp/.buildx-cache,mode=max ; ) ;
+        #run: |
+        #  [[ -f /tmp/.buildx-cache/index.json ]] && echo "Skip run of Docker cache Fix" || echo "FROM alpine" | docker buildx build - --cache-to type=local,dest=/tmp/.buildx-cache,mode=max
+        run: |
+          [ -f /tmp/.buildx-cache/index.json ] || printf "FROM scratch\n" | docker buildx build - --cache-to type=local,dest=/tmp/.buildx-cache,mode=max
+          mv /tmp/.buildx-cache /tmp/.buildx-cache-old
+        shell: bash          
+#      - name: hash matrix.platform-args
+#        run: |
+#          echo ${{ matrix.platform-args }}
+#          echo ${{ matrix.platform-args }} | sed -e 's/[;,]/\n/g' | sort -u > /tmp/.buildx-cache/matrixplatformargs
+#          sha1sum /tmp/.buildx-cache/matrixplatformargs
+#          shasum -a1 /tmp/.buildx-cache/matrixplatformargs
+#          cat /tmp/.buildx-cache/matrixplatformargs
+      # Temp fix1
+      #    https://github.com/docker/buildx/issues/206
+#      - name: cache Fix, if cache does not already exist, create Dockerfile.dummy
+#        run: echo "FROM alpine" > Dockerfile.dummy
+#      - uses: docker/build-push-action@v2
+#        with:
+#          context: .
+#          file: Dockerfile.dummy
+#          platforms: |
+#            linux/amd64
+#          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
+#      - name: cache Fix, Move cache
+#        run: |
+#          set -vx
+#          # delete cache dir if index.json not exist
+#          #[[ -f /tmp/.buildx-cache/index.json ]] || rm -rf /tmp/.buildx-cache
+#          # move dummy docker cache over if index.json not exist
+#          [[ -f /tmp/.buildx-cache/index.json ]] || mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+#      # END workaround for --cache-from fails if cache does not already exist
+#######################################################
+
+      - name: Cut "docker-" form github.repository and convert to lowercase # use with ${{ steps.cut.outputs.repo }}
+        id: cut
+        run: echo "::set-output name=repo::$(echo "${{ github.repository }}" | tr '[A-Z]' '[a-z]' | sed -e 's/\/docker-/\//')"
+        shell: bash
+
+      - name: docker/metadata-action
+        uses: docker/metadata-action@v4.0.1
+        # continue-on-error: true
+        id: meta
+        with:
+          images: |
+            name=ghcr.io/${{ steps.cut.outputs.repo }}
+            name=${{ steps.cut.outputs.repo }}
+          #flavor: |
+          #  latest=${{ matrix.tag-latest }}
+          #  ${{ matrix.tag-args }}
+          flavor: |
+            latest=${{ matrix.tag-latest }}
+            prefix=${{ matrix.tag-args }}
+            suffix=
+          # latest=<auto|true|false>: Handle latest tag (default auto)
+          # prefix=<string>,onlatest=<true|false>: A global prefix for each generated tag and optionally for latest
+          # suffix=<string>,onlatest=<true|false>: A global suffix for each generated tag and optionally for latest
+          tags: |
+            type=schedule,pattern=nightly
+            # handlebars
+            type=schedule,pattern={{date 'YYYYMMDD'}}
+            type=semver,pattern={{version}}
+            type=semver,pattern={{major}}.{{minor}}
+            type=semver,pattern={{major}}
+            type=ref,event=branch
+            type=ref,event=pr
+            type=sha,prefix=${{ matrix.tag-args }}sha-,suffix=,format=short,enable=${{ matrix.tag-sha }}
+
+      - name: Login to GitHub
+        if: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+        uses: docker/login-action@v2.0.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Login to Docker Hub
+        if: ${{ github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+        uses: docker/login-action@v2.0.0
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
       - name: Build and push
-        run: docker buildx build --platform=linux/amd64,linux/arm64 --push --tag=fwilhe2/toybox .
+        id: docker_build
+        uses: docker/build-push-action@v3.0.0
+        with:
+          platforms: ${{ matrix.platform-args }}
+          #"linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/riscv64"
+          #linux/amd64,linux/arm/v7,linux/arm64
+          #push: ${{ matrix.release }}
+          push: ${{ matrix.release && github.event_name != 'pull_request' }} # importent to catch a rogue like PR
+          #push: ${{ ( matrix.release && ( github.event_name != 'pull_request' ) ) }} # importent to catch a rogue like PR
+          #push: ${{ github.event_name != 'pull_request' }}  # importent to catch a rogue like PR
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          #cache-from: type=local,src=/tmp/.buildx-cache
+          cache-from: type=local,src=/tmp/.buildx-cache-old
+          #cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
+          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
+          build-args: ${{ matrix.build-args }}
